In [1]:
import numpy as np
from scipy.linalg import svd

In [2]:
#This function calculates the Eigenvectors corresponding for U and V matrices
def calcMat(M, opc):
    #Case of V Matrix
    if opc == 1:
        newM = np.dot(M.T, M)
    #Case of U Matrix
    if opc == 2:
        newM = np.dot(M, M.T)
    
    eigenvalues, eigenvectors = np.linalg.eig(newM)
    ncols = np.argsort(eigenvalues)[::-1]

    #Case of V Matrix, let's transpose it
    if opc == 1:
        return eigenvectors[:,ncols].T
    #Case of U, return normally
    else: return eigenvectors[:,ncols]
        

#Function that calculates Eigenvalues corresponding to the Sigma Matrix
def calcD(M):
    if (np.size(np.dot(M, M.T)) > np.size(np.dot(M.T, M))):
        newM = np.dot(M.T, M)
    else:
        newM = np.dot(M, M.T)
    
    eigenvalues, eigenvectors = np.linalg.eig(newM)
    eigenvalues = np.sqrt(eigenvalues)
    #Sorting in descending order as the svd function does
    return eigenvalues[::-1]

In [3]:
#Creating our matrix
A = np.array([[4, 2, 0], [1, 5, 6]])

In [4]:
#Calling the corresponding Fuctions and saving the values in variables
Vt = calcMat(A, 1)
U = calcMat(A,2)
Sigma = calcD(A)

In [5]:
print(Vt,"\n")
print(U, "\n")
print(Sigma)

[[-0.26001965 -0.65919758 -0.70558368]
 [-0.89132415 -0.11719389  0.43795758]
 [ 0.37139068 -0.74278135  0.55708601]] 

[[-0.28978415 -0.95709203]
 [-0.95709203  0.28978415]] 

[8.13872588 3.97003036]


In [6]:
U_svd, D, VT = np.linalg.svd(A)
print(VT, "\n")
print(U_svd, "\n")
print(D)

[[ 0.26001965  0.65919758  0.70558368]
 [-0.89132415 -0.11719389  0.43795758]
 [ 0.37139068 -0.74278135  0.55708601]] 

[[ 0.28978415 -0.95709203]
 [ 0.95709203  0.28978415]] 

[8.13872588 3.97003036]
